// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANiv7P2XtQQdmDBx_EjosF-g3-_WXcr7M',
    appId: '1:252558251910:android:34cfeb20e89fde5a0d3e07',
    messagingSenderId: '252558251910',
    projectId: 'mycamp-5236e',
    storageBucket: 'mycamp-5236e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgkPRuLG0vlP2h5pmuO0YyJReLqd-4ttM',
    appId: '1:252558251910:ios:d12eee013e0337100d3e07',
    messagingSenderId: '252558251910',
    projectId: 'mycamp-5236e',
    storageBucket: 'mycamp-5236e.appspot.com',
    androidClientId: '252558251910-dp2dj2j8f21g8d6nclm0jmin7k1jlt11.apps.googleusercontent.com',
    iosClientId: '252558251910-iohbvvql6p4av17h8vuundtiga5hsek2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myCamp',
  );
}
